### ISSUE TITLE
TF Provider Error: mismatch between struct and object: Struct defines fields not found in object: format. 

### ISSUE THREAD

**Issue by tcaddy** [port-labs/terraform-provider-port-labs#101]
I'm getting an error with the https://registry.terraform.io/providers/port-labs/port-labs/latest/docs/resources/port_action#approval_webhook_notification option.

> An unexpected error was encountered trying to convert tftypes.Value into action.ApprovalWebhookNotificationModel. This is always an error in the provider. Please report the following to the provider developer:
>
> mismatch between struct and object: Struct defines fields not found in object: format.

![image](https://github.com/port-labs/terraform-provider-port-labs/assets/280902/fa01100c-c515-45fa-984b-ec0f524fe8ed)

**Comment by tcaddy** [comment]
I've confirmed that the secret from `google_secret_manager_secret_version.secret_data` is OK.

**Comment by tcaddy** [comment]
I can also repro this by adding an action in TF, use ClickOps to edit the action with webhook approval stuff, then trigger a new plan in TF after the drift has occurred.

**Comment by MPTG94** [comment]
Thanks @tcaddy, I'll open a bug in our internal ticketing to keep track of this and we'll update when it is resolved

**Comment by talsabagport** [comment]
Hey @tcaddy, the fix is available in version `1.9.1`

**Comment by tcaddy** [comment]
I can confirm that this has fixed my issue.  However I'll be opening another issue soon for the next problem I am facing with the TF provider regarding the `approval_webhook_notification` option on the `port_action` resource
