### ISSUE TITLE
Missing documentation for `port_action` -> `approval_webhook_notification` option

### ISSUE THREAD

**Issue by tcaddy** [port-labs/terraform-provider-port-labs#108]
The `approval_webhook_notification` option of the `port_action` resource documented here is incomplete: https://registry.terraform.io/providers/port-labs/port-labs/latest/docs/resources/port_action#nested-schema-for-approval_webhook_notification

I had to do ClickOps to setup the Slack option and then run TF to identify the drift in order to find out what the undocumented syntax needs to be:
![image](https://github.com/port-labs/terraform-provider-port-labs/assets/280902/1ed2f67d-cf90-4492-b810-67857d82e048)

**Comment by talsabagport** [comment]
Thanks @tcaddy , fixed in the latest version
