### ISSUE TITLE
port-labs_port_aggregation_properties | count_entities does not have the functionality to allow for a query

### ISSUE THREAD

**Issue by esketch545** [port-labs/terraform-provider-port-labs#173]
In Port, you are able to create a filter something like the query below, but it does not seem possible to replicate this using the port-labs terraform provider. average_entities, average_by_property, and aggregate_by_property all have the ability but count_entities does not for some reason.
{
  "combinator": "and",
  "rules": [
    {
      "property": "status",
      "operator": "in",
      "value": [
        "OPEN",
        "REOPENED"
      ]
    },
    {
      "property": "severity",
      "operator": "=",
      "value": "CRITICAL"
    }
  ]
}

![image](https://github.com/user-attachments/assets/3f19519c-9735-4d1b-94d2-a3470e0c1914)
![image](https://github.com/user-attachments/assets/2278ddf6-f459-4378-8e64-c2996ff77d12)
![image](https://github.com/user-attachments/assets/c236b9e1-fc88-4197-920d-184ba9319e26)
![image](https://github.com/user-attachments/assets/8d4e2b83-ae3f-4cfd-b8c1-fdbb3996a4fd)

**Comment by esketch545** [comment]
![image](https://github.com/user-attachments/assets/a76bdfcb-f35e-4528-8dac-1501e074310e)
Here is the json too!

**Comment by Tankilevitch** [comment]
Hey @esketch545 glad to see you are using port terraform provider :) 

You can define the query filter by passing it using jsonencode into the `query` param which is in the same hierarchy as the `method` param.

https://registry.terraform.io/providers/port-labs/port-labs/latest/docs/resources/port_aggregation_properties#query

See this example:
```
resource "port_aggregation_properties" "repository_aggregation_properties" {
  blueprint_identifier = port_blueprint.repository_blueprint.identifier
  properties           = {
    "fix_pull_requests_count" = {
      target_blueprint_identifier = port_blueprint.pull_request_blueprint.identifier
      title                       = "Pull Requests Per Day"
      icon                        = "Terraform"
      description                 = "Pull Requests Per Day"
      method                      = {
        average_entities = {
          average_of      = "month"
          measure_time_by = "$createdAt"
        }
      }
      query = jsonencode(
        {
          "combinator" : "and",
          "rules" : [
            {
              "property" : "$title",
              "operator" : "ContainsAny",
              "value" : ["fix", "fixed", "fixing", "Fix"]
            }
          ]
        }
      )
    }
  }
}
```

Please feel free the re-open the issue if you have any further questions
