### ISSUE TITLE
Add support for scorecards

### ISSUE THREAD

**Issue by PavelPikat** [port-labs/terraform-provider-port-labs#28]
Hey,

It seems like Terraform resource for managing scorecards is currently missing from the provider, or at least I could not see how to define filters and condition using the available blueprint resource.

Will scorecards be made available as Terraform resource?

**Comment by PavelPikat** [comment]
We ended up using [restapi](https://registry.terraform.io/providers/Mastercard/restapi/latest/docs) provider.
It works pretty well.

Example:

```
terraform {
  required_providers {
    restapi = {
      source  = "Mastercard/restapi"
      version = "=1.18.0"
    }
  }
}

data "external" "port-jwt" {
  program = ["powershell.exe", "${path.module}/files/Get-PortJwt.ps1"]
  query   = {
    clientId     = var.port_client_id
    clientSecret = var.port_api_key
  }
}

data "template_file" "scorecard" {
  template = file("${path.module}/templates/scorecard.json")
}

resource "restapi_object" "scorecard" {
  path = "/v1/blueprints/my-blueprint/scorecards"
  data = data.template_file.scorecard.rendered
}
```

We use external provider to get access token for the restapi provider. We use PowerShell to call Port's REST API to get the token.
Here's the content of PowerShell script used in the example above:

```
$Body = [Console]::In.ReadLine()

$Uri = "https://api.getport.io/v1/auth/access_token"

$Response = Invoke-RestMethod -Uri $Uri -Method Post -Body $Body -ContentType "application/json"

return @{
    accessToken = $Response.accessToken
} | ConvertTo-Json
```

**Comment by gustavobini** [comment]
I have just faced the same issue. Is this planned for anytime soon?

**Comment by dvirsegev** [comment]
We added a support of scorecard resource on version [v1.5.0](https://github.com/port-labs/terraform-provider-port-labs/releases/tag/v1.5.0)
