### ISSUE TITLE
Error - json: cannot unmarshal array into Go struct field Entity.entity.relations of type string

### ISSUE THREAD

**Issue by andrewiankidd** [port-labs/terraform-provider-port-labs#32]
Hi, when I change my blueprint to `many = true`, I start to receive errors when refreshing the state of my existing entity

We deploy multiple 'environments' across a shared server, and I'd like the represent the relationship as a one (server) to many (envs)

I have put together a repro repo here with steps here:
https://github.com/andrewiankidd/terraform-provider-port-labs-issues-32

```
port-labs_blueprint.environment: Refreshing state... [id=testing-env]
port-labs_entity.environment: Refreshing state... [id=testing]
port-labs_blueprint.sql-server: Refreshing state... [id=testing-sql]
port-labs_entity.sql-server: Refreshing state... [id=testing-sql]
╷
│ Error: json: cannot unmarshal array into Go struct field Entity.entity.relations of type string
│
│   with port-labs_entity.sql-server,
│   on entities.tf line 13, in resource "port-labs_entity" "sql-server":
│   13: resource "port-labs_entity" "sql-server" {
│
╵
```

**Comment by dvirsegev** [comment]
Hey @andrewiankidd , Any change that you update the terraform to the latest version?
