### ISSUE TITLE
Force Delete Blueprint and its Entities During Terraform Destroy

### ISSUE THREAD

**Issue by dirien** [port-labs/terraform-provider-port-labs#61]
As an IaC user, I want the ability to force delete a blueprint and its entities during a `terraform destroy` operation, even when the blueprint has existing dependent entities. This feature will help us ensure that infrastructure can be taken down smoothly, without being blocked by dependent entities.

## Current Behavior
At present, during a 'terraform destroy' operation, if there is an existing 'helm-release-blueprint' entity or any other dependents associated with a blueprint, the destroy operation fails and an error message is displayed as follows:

```json
{"ok":false,"error":"has_dependents","message":"This Blueprint cannot be deleted because there are existing \"helm-release-blueprint\" entities","details":{"blueprint":"helm-release-blueprint","entitiesCount":1}}
```

This prevents the blueprint and its associated entities from being destroyed.

## Expected Behavior
We need an additional feature, or an option, to override this dependency check during a `terraform destroy` operation, thereby allowing the blueprint and its entities to be deleted forcefully.

When a user runs 'terraform destroy' with the proposed force delete option, it should delete the blueprint and all its dependent entities without throwing the `has_dependents` error.

##  Use Case
This feature will be very beneficial for cases where we need to decommission an entire environment or individual components which have dependent entities. It will reduce the complexity and time involved in manually deleting each dependent entity before proceeding with the `terraform destroy` operation.

**Comment by dvirsegev** [comment]
Hey @dirien , I agree that we need to add something like this, An efficient approach would be to first add the entities to the state, delete them, and then proceed to delete the blueprints using the 'depends_on' option.

**Comment by Tankilevitch** [comment]
Added support in 0.10.1
