### ISSUE TITLE
Received null value, however the target type cannot handle null values

### ISSUE THREAD

**Issue by gustavobini** [port-labs/terraform-provider-port-labs#73]
I am facing an annoyance when developing modules on top of `port_entity` with string types using the URL format.

```terraform
// blueprint.tf

resource "port_blueprint" "my-blueprint" {
  identifier = "my-blueprint"
  title      = "my-blueprint"
  icon       = "Cloud"

  properties = {
    string_props = {
      my_url = {
        title       = "My Url"
        format      = "url"
      }

      name = {
        title = "Name"
      }
    }
  }
}

// module/main.tf

resource "port_entity" "my-system" {
  blueprint = "my-blueprint"

  identifier = "my-identifier"
  title      = "my-title"
  teams      = tolist(["my-team"])

  properties = {
    string_props = {
      my_url = var.stuff.my_url
      name   = var.stuff.name
    }
  }
}

// module/variables.tf

variable "stuff" {
  type = object({
    "my_url"              = optional(string)
    "name"                = string
  })
}

// thing.tf

module "thing" {
  source = "./module"
  
  thing = {
    "name"   = "my-name"
  }
}

```

Running `terraform apply` causes the following error:

```sh
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Received null value, however the target type cannot handle null values. Use the corresponding `types` package type, a pointer type or a custom type that handles null values.
```

This seems to happen because `my-url` is defined as being a string in Port, so when passing it a null value, it does not accept it. I did also try adding an empty string, however, that also fails because `format = url` rejects it.

**Comment by dvirsegev** [comment]
HI @gustavobini , Thank you very much! I've opened an issue on our side, and it should be resolved by the end of next week

**Comment by dvirsegev** [comment]
Hi @gustavobini , Currently we don't support null values in properties. Can you use conditional to define the object?

**Comment by gustavobini** [comment]
@dvirsegev I did address this issue for my particular case. I thought I'd open an issue as being able to do what's described in the issue is much more "terraformy", but I leave it to you to decide what to do about it.
