### ISSUE TITLE
port_team resource should not force an update because of users order

### ISSUE THREAD

**Issue by PavelPikat** [port-labs/terraform-provider-port-labs#80]
We switched to the latest v1.6.2 version of the provider and tried managing Port teams via `port_team` resource.

We defined users as an array of strings. It creates the team just find.
However, after that, every plan/apply detects changes in the `port_team` resource because the provider things the list of members should be ordered differently. So we end up sending meaningless requests to Port API to update the same list of users, just ordered differently.

I think the `port_team` resource should ignore the order of users array and not report diff

**Comment by dvirsegev** [comment]
Hey @PavelPikat  , Thanks for the feedback! We are currently working on a fix , will ping when it's resolved
