### ISSUE TITLE
[1.7.0] Terraform plan fails to read new dynamic required property in self-service action

### ISSUE THREAD

**Issue by PavelPikat** [port-labs/terraform-provider-port-labs#91]
With the release of new dynamic `required` property, Port's Terraform provider `1.7.0` is now unable to read state for the action (I modified it manually in Port UI), and `terraform plan` is failing now:

```
Error: failed reading action
│ json: cannot unmarshal object into Go struct field
│ .action.userInputs.required of type []string
```

**Comment by Tankilevitch** [comment]
Released in https://github.com/port-labs/terraform-provider-port-labs/releases/tag/v1.8.0
